import type { Device } from "./device";

export const MOCK_DEVICES: Device[] = [
    {
        id: "philips-hue-white-a19",
        name: "Hue White A19",
        manufacturer: "Philips Hue",
        model: "9290011998",
        category: "lighting",
        local: "always",
        cloud: "optional",
        summary: "Standard A19 white bulb. Pairs to a Hue Bridge over Zigbee. Bluetooth used only for setup and direct control without a bridge.",
        reports: 4218,
        installs: 2914,
    },
    {
        id: "ikea-tradfri-led1836g9",
        name: "TRÅDFRI LED bulb E26 800lm",
        manufacturer: "IKEA",
        model: "LED1836G9",
        category: "lighting",
        local: "always",
        cloud: "none",
        summary: "Inexpensive dimmable warm-white bulb. Works with any Zigbee 3.0 coordinator. Does not require the IKEA Trådfri gateway.",
        reports: 2104,
        installs: 1488,
    },
    {
        id: "inovelli-blue-lzw31",
        name: "Blue Series 2-1 Dimmer",
        manufacturer: "Inovelli",
        model: "VZM31-SN",
        category: "controls",
        local: "always",
        cloud: "none",
        summary: "Smart dimmer with notification LED bar. Operates fully local over Zigbee. Supports binding and scene control without a hub manufacturer cloud.",
        reports: 1186,
        installs: 942,
    },
    {
        id: "lifx-color-a19",
        name: "Color A19",
        manufacturer: "LIFX",
        model: "LHA19E26UC10",
        category: "lighting",
        local: "sometimes",
        cloud: "optional",
        summary: "Wi-Fi color bulb. Home Assistant controls it on the LAN via LIFX's UDP protocol. The manufacturer app uses the cloud, but local-only operation works.",
        reports: 1502,
        installs: 1108,
    },
    {
        id: "sengled-element-classic",
        name: "Element Classic A19",
        manufacturer: "Sengled",
        model: "Z01-A19NAE26",
        category: "lighting",
        local: "always",
        cloud: "none",
        summary: "Soft-white A19 bulb. Acts as an end device only, does not route Zigbee mesh traffic. Pair directly to your coordinator.",
        reports: 612,
        installs: 487,
    },
    {
        id: "lutron-caseta-pd-6wcl",
        name: "Caséta Wireless In-Wall Dimmer",
        manufacturer: "Lutron",
        model: "PD-6WCL",
        category: "controls",
        local: "always",
        cloud: "optional",
        summary: "Wall dimmer that talks Lutron's proprietary Clear Connect RF to a Caséta bridge. Home Assistant integrates via the LEAP protocol over LAN. No cloud required after bridge setup.",
        reports: 1810,
        installs: 1402,
    },
    {
        id: "aqara-wall-switch-h1",
        name: "Wall Switch H1 (No Neutral)",
        manufacturer: "Aqara",
        model: "WS-EUK01",
        category: "controls",
        local: "always",
        cloud: "none",
        summary: "Single-gang Zigbee wall switch designed for installations without a neutral wire. Reports power consumption alongside switch state.",
        reports: 988,
        installs: 712,
    },
    {
        id: "shelly-plus-1",
        name: "Plus 1",
        manufacturer: "Shelly",
        model: "SNSW-001X16EU",
        category: "controls",
        local: "always",
        cloud: "optional",
        summary: "Single-channel relay. Exposes a local HTTP API and MQTT. Bluetooth is used for initial provisioning. Cloud is opt-in.",
        reports: 2841,
        installs: 2014,
    },
    {
        id: "sonoff-zbmini-l2",
        name: "ZBMINI-L2",
        manufacturer: "SONOFF",
        model: "ZBMINIL2",
        category: "controls",
        local: "always",
        cloud: "none",
        summary: "Compact in-wall relay. The L2 revision works without a neutral wire. Reports as a non-routing Zigbee end device.",
        reports: 1342,
        installs: 1051,
    },
    {
        id: "aqara-fp2",
        name: "Presence Sensor FP2",
        manufacturer: "Aqara",
        model: "PS-S02D",
        category: "presence",
        local: "sometimes",
        cloud: "required",
        summary: "mmWave presence sensor that maps a room into zones. The Aqara cloud is required for setup. Ongoing operation can be local via HomeKit pairing.",
        reports: 1684,
        installs: 1112,
    },
    {
        id: "aqara-temperature-t1",
        name: "Temperature and Humidity Sensor T1",
        manufacturer: "Aqara",
        model: "WSDCGQ12LM",
        category: "sensors",
        local: "always",
        cloud: "none",
        summary: "Small battery-powered sensor reporting temperature, humidity and pressure. Sleeps between reports to conserve battery.",
        reports: 3214,
        installs: 2461,
    },
    {
        id: "sonoff-snzb-02",
        name: "SNZB-02 Temperature Sensor",
        manufacturer: "SONOFF",
        model: "SNZB-02",
        category: "sensors",
        local: "always",
        cloud: "none",
        summary: "Inexpensive temperature and humidity sensor. Reports roughly every five minutes or on a one-degree threshold change.",
        reports: 2618,
        installs: 1908,
    },
    {
        id: "philips-hue-motion",
        name: "Hue Motion Sensor (indoor)",
        manufacturer: "Philips Hue",
        model: "9290012607",
        category: "presence",
        local: "always",
        cloud: "optional",
        summary: "Battery PIR with built-in lux. Pairs to a Hue Bridge or directly to any Zigbee 3.0 coordinator.",
        reports: 1492,
        installs: 1208,
    },
    {
        id: "ecobee-smartsensor",
        name: "SmartSensor",
        manufacturer: "Ecobee",
        model: "EB-RSHM2PK-01",
        category: "presence",
        local: "never",
        cloud: "required",
        summary: "Room sensor paired to an Ecobee thermostat. Sensor state is read by Home Assistant from the Ecobee cloud, the local thermostat does not expose it.",
        reports: 614,
        installs: 502,
    },
    {
        id: "yale-assure-lock-2",
        name: "Assure Lock 2 (Z-Wave)",
        manufacturer: "Yale",
        model: "YRD420-ZW2",
        category: "security",
        local: "always",
        cloud: "none",
        summary: "Touchscreen deadbolt with a Z-Wave 700-series module. Reports lock and unlock events with the user code that triggered them.",
        reports: 904,
        installs: 712,
    },
    {
        id: "august-wifi-smart-lock",
        name: "Wi-Fi Smart Lock (4th gen)",
        manufacturer: "August",
        model: "AUG-SL05-M02-G02",
        category: "security",
        local: "never",
        cloud: "required",
        summary: "Connects directly to Wi-Fi. Home Assistant uses the August cloud API. Lock state may lag by several seconds.",
        reports: 542,
        installs: 411,
    },
    {
        id: "schlage-encode",
        name: "Encode Wi-Fi Deadbolt",
        manufacturer: "Schlage",
        model: "BE489WB",
        category: "security",
        local: "never",
        cloud: "required",
        summary: "Built-in Wi-Fi deadbolt. The official Home Assistant integration depends on the Schlage cloud. The Encode Plus (Matter) variant works locally.",
        reports: 318,
        installs: 247,
    },
    {
        id: "aqara-u100",
        name: "Smart Lock U100",
        manufacturer: "Aqara",
        model: "ZNMS02LM",
        category: "security",
        local: "sometimes",
        cloud: "optional",
        summary: "Fingerprint and keypad deadbolt. Local control is available when paired via HomeKit. The Aqara mobile app uses the cloud.",
        reports: 412,
        installs: 318,
    },
    {
        id: "roborock-s8-pro-ultra",
        name: "S8 Pro Ultra",
        manufacturer: "Roborock",
        model: "S8PU",
        category: "cleaning",
        local: "sometimes",
        cloud: "required",
        summary: "Robot vacuum and mop. The official integration uses the Roborock cloud. A Valetudo install enables fully local control on supported firmware.",
        reports: 712,
        installs: 588,
    },
    {
        id: "roomba-j7",
        name: "Roomba j7+",
        manufacturer: "iRobot",
        model: "j7558",
        category: "cleaning",
        local: "never",
        cloud: "required",
        summary: "Vacuum cleaner with self-emptying base. Home Assistant talks to the iRobot cloud. Local control is not exposed.",
        reports: 902,
        installs: 718,
    },
    {
        id: "dreame-l10s-ultra",
        name: "L10s Ultra",
        manufacturer: "Dreame",
        model: "L10sU",
        category: "cleaning",
        local: "sometimes",
        cloud: "required",
        summary: "Mop-and-vac with auto-empty dock. Cloud-based by default. Local MQTT control is possible on rooted firmware.",
        reports: 416,
        installs: 322,
    },
    {
        id: "tplink-kasa-hs103",
        name: "Kasa Smart Plug Mini HS103",
        manufacturer: "TP-Link",
        model: "HS103",
        category: "power",
        local: "always",
        cloud: "optional",
        summary: "Wi-Fi smart plug. Older firmware exposed a local protocol used by Home Assistant. Recent firmware may require the cloud, pin to firmware before purchase if local matters.",
        reports: 2210,
        installs: 1788,
    },
    {
        id: "switchbot-plug-mini",
        name: "Plug Mini (W1901500-GH)",
        manufacturer: "SwitchBot",
        model: "W1901500-GH",
        category: "power",
        local: "sometimes",
        cloud: "required",
        summary: "Wi-Fi plug with energy monitoring. The SwitchBot integration uses the cloud API. Local control over Bluetooth works only when in range of a SwitchBot hub.",
        reports: 642,
        installs: 488,
    },
    {
        id: "aqara-smart-plug",
        name: "Smart Plug (EU)",
        manufacturer: "Aqara",
        model: "SP-EUC01",
        category: "power",
        local: "always",
        cloud: "none",
        summary: "Zigbee plug with power and energy reporting. Also acts as a router for the Zigbee mesh.",
        reports: 1218,
        installs: 902,
    },
    {
        id: "shelly-plug-s",
        name: "Plug S Gen3",
        manufacturer: "Shelly",
        model: "S3PL-00112EU",
        category: "power",
        local: "always",
        cloud: "optional",
        summary: "Compact plug with energy metering. Exposes the same local HTTP and MQTT API as the rest of the Shelly Plus/Pro line.",
        reports: 1414,
        installs: 1106,
    },
    {
        id: "home-assistant-skyconnect",
        name: "Home Assistant Connect ZBT-1",
        manufacturer: "Nabu Casa",
        model: "ZBT-1",
        category: "hubs",
        local: "always",
        cloud: "none",
        summary: "USB Zigbee and Thread coordinator. Plugs into a Home Assistant host. No manufacturer cloud is involved.",
        reports: 1908,
        installs: 1488,
    },
    {
        id: "home-assistant-yellow",
        name: "Home Assistant Yellow",
        manufacturer: "Nabu Casa",
        model: "HA-YELLOW-CM4",
        category: "hubs",
        local: "always",
        cloud: "none",
        summary: "Purpose-built Home Assistant appliance with onboard Zigbee/Thread radio and Power-over-Ethernet. Ships with Home Assistant OS.",
        reports: 1108,
        installs: 1108,
    },
    {
        id: "smlight-slzb-06",
        name: "SLZB-06 Ethernet Zigbee Coordinator",
        manufacturer: "SMLight",
        model: "SLZB-06",
        category: "hubs",
        local: "always",
        cloud: "none",
        summary: "PoE Zigbee coordinator with optional Wi-Fi. Connects to Home Assistant over the network so the radio doesn't need to live next to the host.",
        reports: 818,
        installs: 712,
    },
    {
        id: "aqara-hub-m2",
        name: "Hub M2",
        manufacturer: "Aqara",
        model: "ZHWG15LM",
        category: "hubs",
        local: "sometimes",
        cloud: "optional",
        summary: "Aqara's mainstream gateway. Pairs Aqara Zigbee devices and re-exposes them via HomeKit, which Home Assistant can read locally. LAN protocol changes occasionally between firmware versions.",
        reports: 1342,
        installs: 998,
    },
    {
        id: "ecobee-premium",
        name: "Ecobee Premium",
        manufacturer: "Ecobee",
        model: "EB-STATE6-01",
        category: "climate",
        local: "never",
        cloud: "required",
        summary: "Smart thermostat with built-in air quality sensor. Home Assistant control is via the Ecobee cloud. There is no local API.",
        reports: 1102,
        installs: 904,
    },
    {
        id: "honeywell-t9",
        name: "T9 Smart Thermostat",
        manufacturer: "Honeywell Home",
        model: "RCHT9610WFSW",
        category: "climate",
        local: "never",
        cloud: "required",
        summary: "Cloud-only thermostat. The Resideo developer API is rate-limited. Expect occasional unavailability in Home Assistant.",
        reports: 488,
        installs: 402,
    },
    {
        id: "aqara-radiator-e1",
        name: "Radiator Thermostat E1",
        manufacturer: "Aqara",
        model: "SRTS-A01",
        category: "climate",
        local: "always",
        cloud: "none",
        summary: "Battery-powered TRV head. Reports valve position, setpoint and battery. Supports child-lock and window-open detection.",
        reports: 612,
        installs: 488,
    },
    {
        id: "reolink-e1-pro",
        name: "E1 Pro",
        manufacturer: "Reolink",
        model: "E1 Pro",
        category: "cameras",
        local: "always",
        cloud: "optional",
        summary: "Indoor pan-tilt camera with RTSP and ONVIF. Streams directly to Home Assistant on the LAN. Cloud features are opt-in.",
        reports: 514,
        installs: 412,
    },
    {
        id: "wyze-cam-v3",
        name: "Cam v3",
        manufacturer: "Wyze",
        model: "WYZEC3",
        category: "cameras",
        local: "sometimes",
        cloud: "required",
        summary: "Inexpensive 1080p camera. The official integration is cloud-only. RTSP streaming works locally on supported firmware.",
        reports: 716,
        installs: 612,
    },
    {
        id: "sonos-one-gen2",
        name: "Sonos One (Gen 2)",
        manufacturer: "Sonos",
        model: "S18",
        category: "entertainment",
        local: "always",
        cloud: "optional",
        summary: "Wi-Fi speaker controllable on the LAN via the Sonos SOAP API. Streaming services require their own accounts, but local playback and TTS work without the cloud.",
        reports: 1184,
        installs: 902,
    },
    {
        id: "chromecast-gtv-4k",
        name: "Chromecast with Google TV (4K)",
        manufacturer: "Google",
        model: "GA01919",
        category: "entertainment",
        local: "sometimes",
        cloud: "required",
        summary: "Cast target plus an Android TV remote endpoint. Casting is local. App launching depends on Google services and can break across updates.",
        reports: 944,
        installs: 712,
    },
    {
        id: "rachio-3",
        name: "Smart Sprinkler Controller (3rd Gen)",
        manufacturer: "Rachio",
        model: "8ZULW-C",
        category: "irrigation",
        local: "never",
        cloud: "required",
        summary: "Eight-zone Wi-Fi sprinkler controller with weather-based skip. Home Assistant controls it through the Rachio cloud. There is no documented local API.",
        reports: 1284,
        installs: 1042,
    },
    {
        id: "hunter-hydrawise-hc",
        name: "Hydrawise HC Controller",
        manufacturer: "Hunter",
        model: "HC-1200i",
        category: "irrigation",
        local: "never",
        cloud: "required",
        summary: "Twelve-zone Wi-Fi irrigation controller. The official Hydrawise integration polls the manufacturer cloud. No local control path exists on current firmware.",
        reports: 412,
        installs: 318,
    },
    {
        id: "june-oven-gen3",
        name: "June Oven (Gen 3)",
        manufacturer: "June",
        model: "JOV3",
        category: "kitchen",
        local: "never",
        cloud: "required",
        summary: "Counter-top smart oven with internal camera. There is no Home Assistant integration. Control is only via the manufacturer's iOS/Android app over their cloud.",
        reports: 86,
        installs: 74,
    },
    {
        id: "ge-opal-2",
        name: "Opal 2.0 Nugget Ice Maker",
        manufacturer: "GE Profile",
        model: "XPIO13BCBT",
        category: "kitchen",
        local: "sometimes",
        cloud: "optional",
        summary: "Wi-Fi nugget ice maker. The official SmartHQ integration controls it through GE's cloud. Bluetooth control works without internet but only from a phone nearby.",
        reports: 248,
        installs: 196,
    },
    {
        id: "surepetcare-microchip-cat-flap",
        name: "Microchip Cat Flap Connect",
        manufacturer: "Sure Petcare",
        model: "SureFlap MCC",
        category: "pets",
        local: "never",
        cloud: "required",
        summary: "Microchip-reading cat flap with locking modes. State is read from the Sure Petcare cloud. Locking commands round-trip through their service, so latency can spike when their backend is slow.",
        reports: 562,
        installs: 438,
    },
    {
        id: "petlibro-granary-camera",
        name: "Granary Camera Feeder",
        manufacturer: "Petlibro",
        model: "PLAF203",
        category: "pets",
        local: "never",
        cloud: "required",
        summary: "Wi-Fi automatic pet feeder with built-in camera. No Home Assistant integration exists. The manufacturer app is the only supported client and uses their cloud exclusively.",
        reports: 64,
        installs: 58,
    },
    {
        id: "pentair-intellicenter",
        name: "IntelliCenter Pool Control System",
        manufacturer: "Pentair",
        model: "522036",
        category: "pool",
        local: "always",
        cloud: "optional",
        summary: "Pool automation panel for Pentair pumps, heaters, and lights. The official ScreenLogic integration speaks to the panel directly over the LAN. Cloud is optional and used only by the mobile app.",
        reports: 184,
        installs: 152,
    },
    {
        id: "tesla-wall-connector-3",
        name: "Wall Connector (Gen 3)",
        manufacturer: "Tesla",
        model: "1457768-02-J",
        category: "vehicles",
        local: "always",
        cloud: "none",
        summary: "Hard-wired Level-2 EV charger with a built-in HTTP API on its commissioning Wi-Fi network. Home Assistant reads charging state and power directly from the unit. No manufacturer cloud is involved.",
        reports: 386,
        installs: 304,
    },
    {
        id: "ikea-fyrtur-roller",
        name: "FYRTUR Blackout Roller Blind",
        manufacturer: "IKEA",
        model: "E1757",
        category: "shading",
        local: "always",
        cloud: "none",
        summary: "Battery-powered blackout roller blind. Pairs to any Zigbee 3.0 coordinator. Works without the IKEA hub or any cloud service.",
        reports: 1438,
        installs: 1106,
    },
    {
        id: "withings-body-plus",
        name: "Body+ Smart Scale",
        manufacturer: "Withings",
        model: "WBS05",
        category: "wearables",
        local: "never",
        cloud: "required",
        summary: "Wi-Fi body-composition scale. Measurements sync to the Withings cloud and Home Assistant reads them from there, the scale never talks to HA directly.",
        reports: 348,
        installs: 274,
    },
];
